[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 52, in get_splits
    all_train = load_scone("ScoNe/scone_nli/train")
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 72, in load_scone
    data_df = pd.concat(dfs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
127.0.0.1 - - [03/Feb/2024 17:01:56] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 52, in get_splits
    all_train = load_scone("ScoNe/scone_nli/train")
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 72, in load_scone
    data_df = pd.concat(dfs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
127.0.0.1 - - [03/Feb/2024 17:02:30] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [03/Feb/2024 17:03:02] "POST /dspy_backend HTTP/1.1" 200 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [03/Feb/2024 17:03:14] "POST /dspy_backend HTTP/1.1" 200 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [03/Feb/2024 17:03:25] "POST /dspy_backend HTTP/1.1" 200 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 52, in get_splits
    all_train = load_scone("ScoNe/scone_nli/train")
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 72, in load_scone
    data_df = pd.concat(dfs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
127.0.0.1 - - [03/Feb/2024 17:03:37] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 58, in get_splits
    test = load_scone(dirname=f"ScoNe/scone_nli/test")
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 72, in load_scone
    data_df = pd.concat(dfs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
127.0.0.1 - - [03/Feb/2024 17:04:04] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 61, in get_splits
    test = load_scone(dirname=f"ScoNe/scone_nli/test")
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 75, in load_scone
    data_df = pd.concat(dfs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
127.0.0.1 - - [03/Feb/2024 17:04:22] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 64, in get_splits
    test = load_scone(dirname=f"ScoNe/scone_nli/test")
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 78, in load_scone
    data_df = pd.concat(dfs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
127.0.0.1 - - [03/Feb/2024 17:04:35] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
TypeError: cannot unpack non-iterable NoneType object
127.0.0.1 - - [03/Feb/2024 17:04:55] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
TypeError: cannot unpack non-iterable NoneType object
127.0.0.1 - - [03/Feb/2024 17:05:19] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 33, in handle_dspy_backend
    train, dev, test = get_splits()
TypeError: cannot unpack non-iterable NoneType object
127.0.0.1 - - [03/Feb/2024 17:05:42] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [03/Feb/2024 17:05:53] "POST /dspy_backend HTTP/1.1" 200 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [03/Feb/2024 17:07:01] "POST /dspy_backend HTTP/1.1" 200 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 47, in handle_dspy_backend
    cot_fewshot =  bootstrap(train, dev) if NEW else ScoNeCoT().load('data/Bootstrapped/scone-cot_fewshot-turbo-gpt4-demos.json')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/primitives/module.py", line 70, in load
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/Bootstrapped/scone-cot_fewshot-turbo-gpt4-demos.json'
127.0.0.1 - - [03/Feb/2024 17:16:29] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 49, in handle_dspy_backend
    cot_fewshot =  bootstrap(train, dev) if NEW else ScoNeCoT().load('data/Bootstrapped/scone-cot_fewshot-turbo-gpt4-demos.json')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/primitives/module.py", line 70, in load
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/Bootstrapped/scone-cot_fewshot-turbo-gpt4-demos.json'
127.0.0.1 - - [03/Feb/2024 17:17:00] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 53, in handle_dspy_backend
    premade.load('data/Bootstrapped/scone-cot_fewshot-turbo-gpt4-demos.json')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/primitives/module.py", line 70, in load
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/Bootstrapped/scone-cot_fewshot-turbo-gpt4-demos.json'
127.0.0.1 - - [03/Feb/2024 17:19:38] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [03/Feb/2024 17:20:10] "POST /dspy_backend HTTP/1.1" 200 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
Exception on /dspy_backend [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 53, in handle_dspy_backend
    evaluator(cot_fewshot, metric=scone_accuracy)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/evaluate/evaluate.py", line 115, in __call__
    reordered_devset, ncorrect, ntotal = self._execute_single_thread(wrapped_program, devset, display_progress)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/evaluate/evaluate.py", line 42, in _execute_single_thread
    example_idx, example, prediction, score = wrapped_program(idx, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/evaluate/evaluate.py", line 105, in wrapped_program
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/evaluate/evaluate.py", line 97, in wrapped_program
    prediction = program(**example.inputs())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/primitives/program.py", line 29, in __call__
    return self.forward(*args, **kwargs)
  File "/Users/ericfeng/Projects/Startup/dspyReact/flask_backend/app/routes.py", line 130, in forward
    return self.generate_answer(context=context, question=question)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/predict/predict.py", line 60, in __call__
    return self.forward(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/predict/chain_of_thought.py", line 66, in forward
    return super().forward(signature=signature, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dspy/predict/predict.py", line 88, in forward
    x, C = dsp.generate(signature, **config)(x, stage=self.stage)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/primitives/predict.py", line 78, in do_generate
    completions: list[dict[str, Any]] = generator(prompt, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/modules/gpt3.py", line 190, in __call__
    response = self.request(prompt, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/modules/gpt3.py", line 156, in request
    return self.basic_request(prompt, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/modules/gpt3.py", line 129, in basic_request
    response = chat_request(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/modules/gpt3.py", line 270, in chat_request
    return _cached_gpt3_turbo_request_v2_wrapped(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/modules/cache_utils.py", line 17, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/modules/gpt3.py", line 244, in _cached_gpt3_turbo_request_v2_wrapped
    return _cached_gpt3_turbo_request_v2(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/joblib/memory.py", line 655, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/joblib/memory.py", line 598, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/joblib/memory.py", line 856, in call
    output = self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dsp/modules/gpt3.py", line 239, in _cached_gpt3_turbo_request_v2
    return cast(OpenAIObject, openai.ChatCompletion.create(**kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/openai/api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
127.0.0.1 - - [03/Feb/2024 17:20:40] "[35m[1mPOST /dspy_backend HTTP/1.1[0m" 500 -
